# Generated by Django 4.2.5 on 2023-10-11 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                ("role", models.CharField(max_length=16)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
